(function(){
  'use strict';
  var source=window.SEPTEMBER_REVENUE_DATA;if(!source)return;
  var host=document.createElement('div');host.className='import-backdrop';host.id='importBackdrop';
  host.innerHTML='<section class="import-drawer" role="dialog" aria-modal="true" aria-label="导入并更新分析数据"><header class="import-head"><div><h2>导入并更新分析数据</h2><p>图片在浏览器本地OCR；校验通过后同步更新全部经营模块</p></div><button class="import-close" aria-label="关闭">×</button></header><div class="import-body"><input id="importFile" type="file" multiple accept=".png,.jpg,.jpeg,.webp,.csv,.xlsx,.xls" hidden><div class="drop-zone" id="dropZone"><div class="drop-icon">⇧</div><b>拖入营业日报图片或表格</b><span>PNG、JPG、CSV、XLSX · 图片不会上传服务器</span></div><div class="import-steps"><div class="import-step active" data-n="1">上传</div><div class="import-step" data-n="2">识别</div><div class="import-step" data-n="3">校验</div><div class="import-step" data-n="4">确认更新</div></div><section class="import-card"><h3>处理进度</h3><div id="fileList"><div class="file-row"><div class="file-type">提示</div><div><b>等待文件</b><span>建议上传完整表头和清晰日期行</span></div><em>待上传</em></div></div></section><section class="import-card"><h3>识别结果与字段校验</h3><div class="import-result-summary" id="resultSummary">尚未识别数据</div><div class="import-preview" id="importPreview"></div></section><section class="import-card" id="conflictCard" hidden><h3>冲突处理</h3><div class="conflict-box"><b id="conflictTitle"></b><p id="conflictText"></p><div class="choice-row"><button data-choice="existing">保留现有数据</button><button data-choice="incoming">采用新识别数据</button></div></div></section><label class="audit"><input id="auditCheck" type="checkbox" checked> 保存导入来源、更新时间和冲突处理结果；未通过校验的数据不写入看板</label></div><footer class="import-footer"><button class="cancel">取消</button><button class="confirm" disabled>确认并更新全部模块</button></footer></section>';
  document.body.appendChild(host);
  var toast=document.createElement('div');toast.className='demo-toast';document.body.appendChild(toast);
  var dz=host.querySelector('#dropZone'),input=host.querySelector('#importFile'),list=host.querySelector('#fileList'),preview=host.querySelector('#importPreview'),summary=host.querySelector('#resultSummary'),confirm=host.querySelector('.confirm'),conflictCard=host.querySelector('#conflictCard');
  var incoming=[],conflicts=[],choice=null,worker=null,selectedFiles=[];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function close(){host.classList.remove('show')}
  function open(){host.classList.add('show');host.querySelector('.import-drawer').scrollTop=0}
  function step(n){host.querySelectorAll('.import-step').forEach(function(s,i){s.classList.toggle('done',i<n-1);s.classList.toggle('active',i===n-1)})}
  function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(function(){toast.classList.remove('show')},2800)}
  function loadScript(src,test){return new Promise(function(resolve,reject){if(test())return resolve();var old=document.querySelector('script[data-lib="'+src+'"]');if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}var s=document.createElement('script');s.src=src;s.dataset.lib=src;s.onload=resolve;s.onerror=function(){reject(new Error('依赖加载失败'))};document.head.appendChild(s)})}
  function n(v){var x=Number(String(v==null?'':v).replace(/[,，\s万]/g,''));return Number.isFinite(x)?x:null}
  function dateValue(v){if(v instanceof Date&&!isNaN(v)){return v.getFullYear()+'-'+String(v.getMonth()+1).padStart(2,'0')+'-'+String(v.getDate()).padStart(2,'0')}if(typeof v==='number'&&v>40000&&v<60000){var d=new Date(Date.UTC(1899,11,30)+Math.round(v)*86400000);return d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0')+'-'+String(d.getUTCDate()).padStart(2,'0')}var m=String(v||'').match(/(?:2026[.\-/年])?0?9[.\-/月](\d{1,2})/);return m?'2026-09-'+String(+m[1]).padStart(2,'0'):''}
  function weekday(date){return ['周日','周一','周二','周三','周四','周五','周六'][new Date(date+'T12:00:00').getDay()]}
  function makeRow(date,a){return {date:date,weekday:weekday(date),outpatient:a[0],inpatient:a[3],first:a[1],repeat:a[2],ward:a[4],admit:a[5],dischargeFirst:a[6],dischargeRepeat:a[7],total:a[8],cumulative:a[9]}}
  function validRow(r){return r&&r.date&&[r.outpatient,r.inpatient,r.first,r.repeat,r.ward,r.admit,r.dischargeFirst,r.dischargeRepeat,r.total,r.cumulative].every(function(v){return Number.isFinite(v)})&&Math.abs(r.outpatient+r.inpatient-r.total)<=2}
  function parseText(text){var rows=[];String(text||'').replace(/[|｜]/g,' ').split(/\n+/).forEach(function(line){var date=dateValue(line);if(!date)return;var rest=line.replace(/(?:2026[.\-/年])?0?9[.\-/月]\d{1,2}日?/,' ').replace(/周?[一二三四五六日天]/,' ');var nums=(rest.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number),a=null;if(nums.length>=12){var z=nums.slice(-12);a=[z[0],z[2],z[3],z[4],z[6],z[7],z[8],z[9],z[10],z[11]]}else if(nums.length===10){a=nums}var r=a&&makeRow(date,a);if(validRow(r))rows.push(r)});return dedupe(rows)}
  function dedupe(rows){var map={};rows.forEach(function(r){map[r.date]=r});return Object.keys(map).sort().map(function(k){return map[k]})}
  function mapObject(o){var pick=function(names){for(var i=0;i<names.length;i++)if(o[names[i]]!=null&&o[names[i]]!=='')return o[names[i]];return null};var date=dateValue(pick(['日期','date','Date']));if(!date)return null;var row={date:date,weekday:weekday(date),outpatient:n(pick(['门诊收入','outpatient'])),inpatient:n(pick(['在院收入','住院收入','inpatient'])),first:n(pick(['初诊','first'])),repeat:n(pick(['复诊','repeat'])),ward:n(pick(['在院','在院人数','ward'])),admit:n(pick(['入院','入院人数','admit'])),dischargeFirst:n(pick(['出院初次','出院第一次','dischargeFirst'])),dischargeRepeat:n(pick(['出院多次','dischargeRepeat'])),total:n(pick(['当日收入合计','当日合计','total'])),cumulative:n(pick(['当月累计收入','月累计','cumulative']))};return validRow(row)?row:null}
  function splitDelimited(line,delimiter){if(delimiter==='\t')return line.split('\t').map(function(x){return x.trim()});var cells=[],cell='',quoted=false;for(var i=0;i<line.length;i++){var ch=line[i];if(ch==='"'&&quoted&&line[i+1]==='"'){cell+='"';i++}else if(ch==='"'){quoted=!quoted}else if(ch===delimiter&&!quoted){cells.push(cell.trim());cell=''}else cell+=ch}cells.push(cell.trim());return cells}
  function parseCsv(text){var lines=String(text).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return [];var delimiter=(lines[0].match(/\t/g)||[]).length>(lines[0].match(/,/g)||[]).length?'\t':',';var head=splitDelimited(lines[0],delimiter);return dedupe(lines.slice(1).map(function(line){var cells=splitDelimited(line,delimiter),o={};head.forEach(function(h,i){o[h]=cells[i]});return mapObject(o)}).filter(Boolean))}
  function prepareImage(file){return new Promise(function(resolve,reject){var img=new Image(),url=URL.createObjectURL(file);img.onload=function(){var scale=img.width<1800?Math.min(2.5,1800/img.width):1,canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);var c=canvas.getContext('2d');c.filter='grayscale(1) contrast(1.25)';c.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas)};img.onerror=reject;img.src=url})}
  async function parseImage(file,onProgress){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',function(){return !!window.Tesseract});if(!worker)worker=await window.Tesseract.createWorker('chi_sim+eng',1,{logger:function(m){if(m.status==='recognizing text')onProgress(Math.round((m.progress||0)*100))}});var image=await prepareImage(file),result=await worker.recognize(image,{rotateAuto:true});return parseText(result.data.text)}
  async function parseWorkbook(file){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',function(){return !!window.XLSX});var wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]],json=XLSX.utils.sheet_to_json(sheet,{defval:''});return dedupe(json.map(mapObject).filter(Boolean))}
  function renderPreview(){var existing={};source.rows.forEach(function(r){existing[r.date]=r});conflicts=incoming.filter(function(r){var x=existing[r.date];return x&&['outpatient','inpatient','first','repeat','ward','admit','dischargeFirst','dischargeRepeat','total','cumulative'].some(function(k){return Number(x[k])!==Number(r[k])})});summary.innerHTML='<b>识别 '+incoming.length+' 个有效日期</b><span> · 新增 '+incoming.filter(function(r){return !existing[r.date]}).length+' · 冲突 '+conflicts.length+' · 校验通过 '+incoming.length+'</span>';preview.innerHTML=incoming.length?'<div class="mcr-table-wrap"><table class="mcr-table"><thead><tr><th>日期</th><th>门诊</th><th>住院</th><th>初诊</th><th>复诊</th><th>入院</th><th>出院</th><th>在院</th><th>当日合计</th><th>状态</th></tr></thead><tbody>'+incoming.map(function(r){var conflict=conflicts.indexOf(r)>-1;return '<tr><td>'+esc(r.date)+'</td><td>'+r.outpatient.toFixed(2)+'</td><td>'+r.inpatient.toFixed(2)+'</td><td>'+r.first+'</td><td>'+r.repeat+'</td><td>'+r.admit+'</td><td>'+(r.dischargeFirst+r.dischargeRepeat)+'</td><td>'+r.ward+'</td><td><b>'+r.total.toFixed(2)+'</b></td><td><span class="tag">'+(conflict?'冲突':'通过')+'</span></td></tr>'}).join('')+'</tbody></table></div>':'<p class="conflict-box">没有识别出可安全写入的完整日期行。请上传清晰的完整表格截图，或使用带标准表头的CSV/XLSX。</p>';conflictCard.hidden=!conflicts.length;if(conflicts.length){host.querySelector('#conflictTitle').textContent='发现 '+conflicts.length+' 个已有日期冲突';host.querySelector('#conflictText').textContent='冲突日期：'+conflicts.map(function(r){return r.date}).join('、')+'。请选择保留现值或采用新识别值。'}choice=conflicts.length?null:'incoming';confirm.disabled=!incoming.length||!!conflicts.length;step(3)}
  async function handle(files){if(!files||!files.length)return;selectedFiles=Array.from(files);incoming=[];conflicts=[];choice=null;confirm.disabled=true;list.innerHTML='';preview.innerHTML='';summary.textContent='正在识别…';step(2);for(var i=0;i<selectedFiles.length;i++){let f=selectedFiles[i],row=document.createElement('div');row.className='file-row';row.innerHTML='<div class="file-type '+(/^image\//.test(f.type)?'image':'')+'">'+(/^image\//.test(f.type)?'IMG':esc((f.name.split('.').pop()||'FILE').toUpperCase()))+'</div><div><b>'+esc(f.name)+'</b><span>'+Math.max(1,Math.round(f.size/1024))+' KB · 准备识别</span></div><em>处理中</em>';list.appendChild(row);try{var parsed=[];if(/^image\//.test(f.type))parsed=await parseImage(f,function(p){row.querySelector('span').textContent='本地OCR '+p+'%'});else if(/\.csv$/i.test(f.name))parsed=parseCsv(await f.text());else if(/\.xlsx?$/i.test(f.name))parsed=await parseWorkbook(f);else throw new Error('不支持的文件类型');incoming=incoming.concat(parsed);row.querySelector('span').textContent='识别到 '+parsed.length+' 个有效日期';row.querySelector('em').textContent=parsed.length?'已识别':'待核';row.querySelector('em').className=parsed.length?'status-ok':''}catch(err){row.querySelector('span').textContent=err.message||'识别失败';row.querySelector('em').textContent='失败';row.querySelector('em').className='status-bad'}}incoming=dedupe(incoming);renderPreview()}
  function mergeRows(){var map={};source.rows.forEach(function(r){map[r.date]=r});incoming.forEach(function(r){if(!map[r.date]||choice==='incoming')map[r.date]=r});var rows=Object.keys(map).sort().map(function(k){return map[k]});for(var i=0;i<rows.length;i++){var prev=i?rows[i-1].cumulative:0;if(Math.abs(prev+rows[i].total-rows[i].cumulative)>2)throw new Error(rows[i].date+'累计金额无法连续勾稽')}return rows}
  host.querySelector('.import-close').onclick=close;host.querySelector('.cancel').onclick=close;host.addEventListener('click',function(e){if(e.target===host)close()});dz.onclick=function(){input.click()};['dragenter','dragover'].forEach(function(x){dz.addEventListener(x,function(e){e.preventDefault();dz.classList.add('drag')})});['dragleave','drop'].forEach(function(x){dz.addEventListener(x,function(e){e.preventDefault();dz.classList.remove('drag')})});dz.addEventListener('drop',function(e){handle(e.dataTransfer.files)});input.addEventListener('change',function(){handle(input.files)});
  host.querySelectorAll('[data-choice]').forEach(function(b){b.onclick=function(){host.querySelectorAll('[data-choice]').forEach(function(x){x.classList.toggle('active',x===b)});choice=b.dataset.choice;confirm.disabled=!incoming.length;confirm.textContent=choice==='existing'?'保留现值并更新新增日期':'采用识别值并更新全部模块'}});
  confirm.onclick=function(){try{var merged=mergeRows();window.updateSeptemberRevenueData(merged,{source:'用户拖拽导入：'+selectedFiles.map(function(f){return f.name}).join('、')});step(4);close();notify('已更新 '+incoming.length+' 个日期；主看板、营销与财务模块已同步重算')}catch(err){summary.innerHTML='<b style="color:#d84c64">未写入：</b>'+esc(err.message);confirm.disabled=true}};
  document.addEventListener('keydown',function(e){if(e.key==='Escape'&&host.classList.contains('show'))close()});window.addEventListener('beforeunload',function(){if(worker&&worker.terminate)worker.terminate()});
  var v2=document.querySelector('.mkt-import');if(v2)v2.onclick=open;var tools=document.querySelector('.sales-month-tools');if(tools&&!tools.querySelector('.data-update-btn')){var b=document.createElement('button');b.className='data-update-btn';b.innerHTML='⇧ 更新数据';b.onclick=open;tools.prepend(b)}var edit=document.getElementById('salesEdit');if(edit)edit.onclick=open;var nursing=document.getElementById('sideNursingPerf');if(nursing)nursing.remove();window.openDataImport=open;window.DASHBOARD_IMPORT_API={parseText:parseText,parseCsv:parseCsv,mapObject:mapObject,validRow:validRow,mergeRows:mergeRows};
})();
